{
	"version": 1662087683,
	"fileList": [
		"falta-data.js",
		"falta-c2runtime.js",
		"jquery-3.4.1.min.js",
		"falta-offlineClient.js",
		"images-falta/sprite-sheet0.png",
		"images-falta/alvo-sheet0.png",
		"images-falta/goleiro-sheet0.png",
		"images-falta/goleiro-sheet1.png",
		"images-falta/goleiro-sheet2.png",
		"images-falta/bola-sheet0.png",
		"images-falta/direita-sheet0.png",
		"images-falta/direita-sheet1.png",
		"images-falta/esquerda-sheet0.png",
		"images-falta/meio-sheet0.png",
		"images-falta/meio-sheet1.png",
		"images-falta/seta-sheet0.png",
		"images-falta/esquerda1-sheet0.png",
		"images-falta/sprite2-sheet0.png",
		"images-falta/sprite3-sheet0.png",
		"images-falta/sprite4-sheet0.png",
		"images-falta/sprite5-sheet0.png",
		"images-falta/sprite6-sheet0.png",
		"images-falta/sprite7-sheet0.png",
		"media/som_gol (online-audio-converter.com).m4a",
		"media/som_gol (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png"
	]
}