{
	"version": 1663182207,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/alvo-sheet0.png",
		"images/goleiro-sheet0.png",
		"images/goleiro-sheet1.png",
		"images/goleiro-sheet2.png",
		"images/bola-sheet0.png",
		"images/direita-sheet0.png",
		"images/esquerda-sheet0.png",
		"images/meio-sheet0.png",
		"images/seta-sheet0.png",
		"images/esquerda1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/spritefont.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"media/som_gol (online-audio-converter.com).m4a",
		"media/som_gol (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}