</table></div></td><td valign='top' align='center'><table cellpadding='0' cellspacing='0' border=0 height=20>
	<tr><td><div style="position:relative;top:0;left:0;width:623;height:57;"><div style="width:623;height:57;background-image:url('img/layout/menu/topH.png');text-aling:center;"><div class="nosel" style="position:absolute;text-align:center;width:623;top:10;color:#515151;font-family:litoh;font-size:1em;">Divisão de jogadores</div><div style="position:absolute;text-align:center;width:623;top:9;color:#e8f4e1;font-family:litoh;font-size:1em;">Divisão de jogadores</div></div></div></td></tr>
	<tr><td><div style="position:relative;top:0;left:0;width:623;min-height:300px; height:auto !important;  height:300px;background-image:url('img/layout/menu/midH.png');padding-top:8;">
<div style='position:relative;top:0;left:0;width:607;margin-left:9;'>
<table width=460 cellpadding="0" cellspacing=3 class="helv" align="center" >
	<tr><td>
		A divisão de jogadores acontece todas as rodadas, 20% melhores sobem, 20% piores rebaixam.<br>
		O melhor jogador se consagra campeão da divisão.<br>
		Detalhes: Caso fique entre 14~2 players , sobe apenas 1 e desce apenas 1.<br>
		Caso fique apenas 1 na divisão , este não sobe e nem cai.<br>
	</td></tr>
	<tr><td>
		<img src="img/faqdivp.png" border=0>
	</tr></td>
	<tr><td>
		<table style="border-width: 3px;border-style: solid;border-color: #148e0a;" width=460 height='1' cellpadding='0' cellspacing='5' class='frezeSoft'><tr><td>
10 primeiros da divisão.
</td></tr></table>
	</tr></td>
	<tr><td>
		<table style="border-width: 3px;border-style: solid;border-color: #0b188e;" width=460 height='1' cellpadding='0' cellspacing='5' class='frezeSoft'><tr><td>
Quantidade minima de gols para subir. A 1ª divisão não tem ascensão
</td></tr></table>
	</tr></td>
	<tr><td>
		<table style="border-width: 3px;border-style: solid;border-color: #1cadb6;" width=460 height='1' cellpadding='0' cellspacing='5' class='frezeSoft'><tr><td>
Quantidade minima de gols para não cair. A 10ª divisão não tem rebaixamento
</td></tr></table>
	</tr></td>
	<tr><td>
		<table style="border-width: 3px;border-style: solid;border-color: #f12525;" width=460 height='1' cellpadding='0' cellspacing='5' class='frezeSoft'><tr><td>
Quantidade total de jogadores nesta divisão, destes 20% sobem, 20% rebaixam.
</td></tr></table>
	</tr></td>
	<tr><td>
		<table style="border-width: 3px;border-style: solid;border-color: #f125ee;" width=460 height='1' cellpadding='0' cellspacing='5' class='frezeSoft'><tr><td>
Status se você participa ou não desta divisão , e se você esta (permanecendo/subindo/caindo).
</td></tr></table>
	</tr></td>
	<tr><td align="center">
	<Font size=5><b>Habilidades</b></font>
	</td></tr>
	<tr><td>
	<table width=460 height='1' border='0' align='center' valign='top' cellpadding='0' cellspacing='5' class='frezeSoft'><tr><td colspan='2'><font size=4><b>Habilidades de chute</b></font></td></tr><tr><td valign='top'> <table width=260 height='1' border='0' align='center' valign='top' cellpadding='0' cellspacing='0' class='frezeSoft'>
<tr><td colspan='2'><table class='frezeSoft' border='0' cellpadding='0' cellspacing='2' ><tr><td><img src='img/hab1.png' border=0></td><td><font size='2'><b>Penalti</b></font></td></tr></table></tr>
<tr bgcolor='#4D4D4D' class='dest'><td width=40 style='padding-left:7px'>Nivel</td><td>Chance</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>1</td><td>54%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>2</td><td>58%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>3</td><td>62%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>4</td><td>66%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>5</td><td>70%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>6</td><td>74%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>7</td><td>78%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>8</td><td>82%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>9</td><td>86%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>10</td><td>90%</td></tr></table> </td><td valign='top' style='padding-top:25'>Principal habilidade de chute, cada nivel aumenta a chance de acerto em 4%<br> Minimo 54% <br> Maximo 90% <br><br> Tempo de espera:<br> 10 minutos<br> 5 minutos vip</td></tr><tr><td valign='top'> <table width=260 height='1' border='0' align='center' valign='top' cellpadding='0' cellspacing='0' class='frezeSoft'>
<tr><td colspan='2'><table class='frezeSoft' border='0' cellpadding='0' cellspacing='2' ><tr><td><img src='img/hab2.png' border=0></td><td><font size='2'><b>Falta</b></font></td></tr></table></td></tr>
<tr bgcolor='#4D4D4D' class='dest'><td width=40 style='padding-left:7px'>Nivel</td><td>Chance</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>1</td><td>34%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>2</td><td>38%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>3</td><td>42%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>4</td><td>46%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>5</td><td>50%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>6</td><td>54%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>7</td><td>58%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>8</td><td>62%</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>9</td><td>66%</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>10</td><td>70%</td></tr></table> </td><td valign='top' style='padding-top:25'>Habilidade muito importante de chute, cada nivel aumenta a chance de acerto em 4%<br> Minimo 34% <br> Maximo 70% <br><br> Tempo de espera:<br> 10 minutos<br> 5 minutos vip</td></tr><tr><td valign='top'> <table width=260 height='1' border='0' align='center' valign='top' cellpadding='0' cellspacing='0' class='frezeSoft'>
<tr><td colspan='2'><table class='frezeSoft' border='0' cellpadding='0' cellspacing='2' ><tr><td><img src='img/hab3.png' border=0></td><td><font size='2'><b>Trilha</b></font></td></tr></table></td></tr>
<tr bgcolor='#4D4D4D' class='dest'><td width=40 style='padding-left:7px'>Nivel</td><td>Redução de Tempo</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>1</td><td>0</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>2</td><td>-17</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>3</td><td>-34</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>4</td><td>-51</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>5</td><td>-68</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>6</td><td>-85</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>7</td><td>-102</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>8</td><td>-119</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>9</td><td>-136</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>10</td><td>-153</td></tr></table> </td><td valign='top' style='padding-top:25'>Habilidade de chute de curto tempo de espera, porem a chance maxima é de 12,5%, cada nivel diminue o tempo de espera em 17 segundos com exceção do primeiro nivel<br><br> Tempo de espera:<br>Maximo 10 minutos <br>Minimo 7:30 minutos <br><br>Maximo 5 minutos vip<br>Minimo 2:30 minutos vip</td></tr><tr><td colspan='2'><font size=4><b>Habilidades de Ajuda</b></font></td></tr><tr><td valign='top'> <table width=260 height='1' border='0' align='center' valign='top' cellpadding='0' cellspacing='0' class='frezeSoft'>
<tr><td colspan='2'><table class='frezeSoft' border='0' cellpadding='0' cellspacing='2' ><tr><td><img src='img/hab4.png' border=0></td><td><font size='2'><b>Blessing de Tempo</b></font></td></tr></table></td></tr>
<tr bgcolor='#4D4D4D' class='dest'><td width=40 style='padding-left:7px'>Nivel</td><td>Tempo de espera</td><td>Duração</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>1</td><td>12 horas</td><td>2 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>2</td><td>10 horas</td><td>2 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>3</td><td>9 horas</td><td>3 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>4</td><td>8 horas</td><td>3 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>5</td><td>7 horas</td><td>4 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>6</td><td>6 horas</td><td>4 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>7</td><td>5 horas</td><td>5 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>8</td><td>4 horas</td><td>5 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>9</td><td>3 horas</td><td>6 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>10</td><td>2 horas</td><td>6 horas</td></tr></table> </td><td valign='top' style='padding-top:25'>Boa habilidade de ajuda.<br> Reduz 60 segundos o tempo de espera da falta e do penalti.<br>Só pode utilizar em você ou jogadores do seu time<br>Requer nivel 30, com todas habilidades de chute.<br>Só pode ser usada em jogadores com nivel 25 ou mais<br>Não pode usar em alguem que esteja com este benefício</td></tr><tr><td valign='top'> <table width=260 height='1' border='0' align='center' valign='top' cellpadding='0' cellspacing='0' class='frezeSoft'>
<tr><td colspan='2'><table class='frezeSoft' border='0' cellpadding='0' cellspacing='2' ><tr><td><img src='img/hab5.png' border=0></td><td><font size='2'><b>Blessing de Falta</b></font></td></tr></table></td></tr>
<tr bgcolor='#4D4D4D' class='dest'><td width=40 style='padding-left:7px'>Nivel</td><td>Tempo de espera</td><td>Duração</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>1</td><td>12 horas</td><td>2 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>2</td><td>10 horas</td><td>2 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>3</td><td>9 horas</td><td>3 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>4</td><td>8 horas</td><td>3 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>5</td><td>7 horas</td><td>4 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>6</td><td>6 horas</td><td>4 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>7</td><td>5 horas</td><td>5 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>8</td><td>4 horas</td><td>5 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>9</td><td>3 horas</td><td>6 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>10</td><td>2 horas</td><td>6 horas</td></tr></table> </td><td valign='top' style='padding-top:25'>Boa habilidade de ajuda.<br> Aumento em 10% na chance de acerto da falta.<br> Só pode utilizar em você ou jogadores do seu time<br>Requer nivel 30, com todas habilidades de chute.<br>Só pode ser usada em jogadores com nivel 25 ou mais<br>Não pode usar em alguem que esteja com este benefício</td></tr><tr><td valign='top'> <table width=260 height='1' border='0' align='center' valign='top' cellpadding='0' cellspacing='0' class='frezeSoft'>
<tr><td colspan='2'><table class='frezeSoft' border='0' cellpadding='0' cellspacing='2' ><tr><td><img src='img/hab6.png' border=0></td><td><font size='2'><b>Blessing de Trilha</b></font></td></tr></table></td></tr>
<tr bgcolor='#4D4D4D' class='dest'><td width=40 style='padding-left:7px'>Nivel</td><td>Tempo de espera</td><td>Duração</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>1</td><td>12 horas</td><td>2 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>2</td><td>10 horas</td><td>2 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>3</td><td>9 horas</td><td>3 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>4</td><td>8 horas</td><td>3 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>5</td><td>7 horas</td><td>4 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>6</td><td>6 horas</td><td>4 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>7</td><td>5 horas</td><td>5 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>8</td><td>4 horas</td><td>5 horas</td></tr><tr bgcolor='#DBDBDB'><td style='padding-left:7px'>9</td><td>3 horas</td><td>6 horas</td></tr><tr bgcolor='#F3F3F3'><td style='padding-left:7px'>10</td><td>2 horas</td><td>6 horas</td></tr></table> </td><td valign='top' style='padding-top:25'>Boa habilidade de ajuda.<br> Muda a ultima linha da trilha, para 2 acerto e 1 erro (2/3).<br> Só pode utilizar em você ou jogadores do seu time<br>Requer nivel 30, com todas habilidades de chute.<br>Só pode ser usada em jogadores com nivel 25 ou mais<br>Não pode usar em alguem que esteja com este benefício</td></tr></table>
	</td></tr>
</table>    
</div></div></td></tr>
<tr><td><div style="position:relative;top:0;width:623;left:0;height:15px;"><img src='img/layout/menu/botH.png' border=0></div></td></tr>
	</table>
